server:
  port: 9935    
spring:
  banner:
    location: classpath:hisBanner.txt
  datasource:
    url: jdbc:h2:mem:HIS
    driver-class-name: org.h2.Driver
    username: HIS
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  mail:
    host: smtp.gmail.com
    port: 587
    username: ip6.sam@gmail.com
    password: itdwnvnzphmiosmj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
