server:
  port: 9935    
spring:
  datasource:
    url: jdbc:h2:mem:HIS
    driver-class-name: org.h2.Driver
    username: HIS
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect  mvc:    view:      prefix: /views/
      suffix: .jsp
  mail:
    host: smtp.gmail.com
    username: sam9695654346@gmail.com
    password: Sam*gmail@9695
# Other properties
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
# TLS , port 587
          starttls:
            enable: true

# SSL, post 465
#spring.mail.properties.mail.smtp.socketFactory.port = 465
#spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFactory      
    
