server:
  port: 9935    
spring:
  datasource:
    url: jdbc:h2:mem:HIS
    driver-class-name: org.h2.Driver
    username: HIS
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  mail:
    host: smtp.gmail.com
    username: sam9695654346@gmail.com
    password: Gmail*sam@9695
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          starttls:
            enable: true
    port: 587

# SSL, post 465
#spring.mail.properties.mail.smtp.socketFactory.port = 465
#spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFactory      
    

# SSL, post 465
#spring.mail.properties.mail.smtp.socketFactory.port = 465
#spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFactory      
    
